repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
      - id: destroyed-symlinks
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: poetry-export-prod
        name: poetry-export-prod
        entry: poetry export -f requirements.txt --output requirements.txt
        language: system
        types: [file]
        files: pyproject.toml
        pass_filenames: false
      - id: poetry-export-dev
        name: poetry-export-dev
        entry: poetry export -f requirements.txt --output requirements-dev.txt --with=dev
        language: system
        types: [file]
        files: pyproject.toml
        pass_filenames: false
